/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'homepage': RouteRecordInfo<'homepage', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-loads-detail': RouteRecordInfo<'admin-loads-detail', '/admin/loads/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-loads-edit': RouteRecordInfo<'admin-loads-edit', '/admin/loads/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'admin-loads-create': RouteRecordInfo<'admin-loads-create', '/admin/loads/create', Record<never, never>, Record<never, never>>,
    'admin-logs': RouteRecordInfo<'admin-logs', '/admin/logs', Record<never, never>, Record<never, never>>,
    'admin-settings': RouteRecordInfo<'admin-settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/auth/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    'signin': RouteRecordInfo<'signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    'signout': RouteRecordInfo<'signout', '/auth/signout', Record<never, never>, Record<never, never>>,
    'checkout': RouteRecordInfo<'checkout', '/checkout', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/NotFound', Record<never, never>, Record<never, never>>,
    'payment-cancel': RouteRecordInfo<'payment-cancel', '/payment/cancel', Record<never, never>, Record<never, never>>,
    'checkout-slug': RouteRecordInfo<'checkout-slug', '/payment/checkout', Record<never, never>, Record<never, never>>,
    'payment-success': RouteRecordInfo<'payment-success', '/payment/success', Record<never, never>, Record<never, never>>,
    'verify-token': RouteRecordInfo<'verify-token', '/verify/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'homepage'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/dashboard.vue': {
      routes: 'admin-dashboard'
      views: never
    }
    'src/pages/admin/loads/[id]/index.vue': {
      routes: 'admin-loads-detail'
      views: never
    }
    'src/pages/admin/loads/[id]/edit.vue': {
      routes: 'admin-loads-edit'
      views: never
    }
    'src/pages/admin/loads/create.vue': {
      routes: 'admin-loads-create'
      views: never
    }
    'src/pages/admin/logs.vue': {
      routes: 'admin-logs'
      views: never
    }
    'src/pages/admin/settings.vue': {
      routes: 'admin-settings'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: 'register'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: 'reset-password'
      views: never
    }
    'src/pages/auth/signin.vue': {
      routes: 'signin'
      views: never
    }
    'src/pages/auth/signout.vue': {
      routes: 'signout'
      views: never
    }
    'src/pages/checkout.vue': {
      routes: 'checkout'
      views: never
    }
    'src/pages/NotFound.vue': {
      routes: 'not-found'
      views: never
    }
    'src/pages/payment/cancel.vue': {
      routes: 'payment-cancel'
      views: never
    }
    'src/pages/payment/checkout.vue': {
      routes: 'checkout-slug'
      views: never
    }
    'src/pages/payment/success.vue': {
      routes: 'payment-success'
      views: never
    }
    'src/pages/verify/[token].vue': {
      routes: 'verify-token'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
